### ISSUE TITLE
ValueError: Unknown cursor kind 601 on macOS

### ISSUE THREAD

**Issue by xgdgsc** [jessevdk/cldoc#121]
I get following error with cldoc on macOS sierra:

```
Traceback (most recent call last):
  File "/usr/local/bin/cldoc", line 9, in <module>
    load_entry_point('cldoc==1.9', 'console_scripts', 'cldoc')()
  File "/usr/local/lib/python2.7/site-packages/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/usr/local/lib/python2.7/site-packages/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/usr/local/lib/python2.7/site-packages/cldoc/cmdgenerate.py", line 125, in run
    t.process()
  File "/usr/local/lib/python2.7/site-packages/cldoc/tree.py", line 212, in process
    self.visit(tu.cursor.get_children())
  File "/usr/local/lib/python2.7/site-packages/cldoc/tree.py", line 517, in visit
    self.visit(item.get_children(), node)
  File "/usr/local/lib/python2.7/site-packages/cldoc/tree.py", line 483, in visit
    if item.kind == cindex.CursorKind.UNEXPOSED_DECL:
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 1189, in kind
    return CursorKind.from_id(self._kind_id)
  File "/usr/local/lib/python2.7/site-packages/cldoc/clang/cindex.py", line 553, in from_id
    raise ValueError,'Unknown cursor kind %d' % id
ValueError: Unknown cursor kind 601
```

Any clue on how I could fix this? The python is python2 installed from brew.

**Comment by kirbyfan64** [comment]
What files are you generating docs for?

**Comment by xgdgsc** [comment]
My hpp and cpp files.

**Comment by xgdgsc** [comment]
Same error with the same files on manjaro linux.
