### ISSUE TITLE
'friend class Bar' causes "ValueError: Unknown template argument kind 603"

### ISSUE THREAD

**Issue by troelsfr** [jessevdk/cldoc#129]
Following code:

```
class Bar;

class Foo {
  int x;
  friend class Bar;
};

class Bar {
  void apply(Foo &foo) { foo.x = 2; }
};
```
gives following error message:

```
$ cldoc generate --std=c++11 -- --output Docs/ test.hpp 
Processing test.hpp
Traceback (most recent call last):
  File "/opt/local/bin/cldoc", line 4, in <module>
    run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/cmdgenerate.py", line 125, in run
    t.process()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/tree.py", line 212, in process
    self.visit(tu.cursor.get_children())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/tree.py", line 517, in visit
    self.visit(item.get_children(), node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/tree.py", line 483, in visit
    if item.kind == cindex.CursorKind.UNEXPOSED_DECL:
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/clang/cindex.py", line 1292, in kind
    return CursorKind.from_id(self._kind_id)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cldoc-1.9-py2.7.egg/cldoc/clang/cindex.py", line 574, in from_id
    raise ValueError,'Unknown template argument kind %d' % id
ValueError: Unknown template argument kind 603
```
I am using the latest checkout on a Mac with Python 2.7

**Comment by petabytestorage** [comment]
i am stuck on this too

**Comment by jessevdk** [comment]
This should be resolved now.
