### ISSUE TITLE
AttributeError: 'TemplateType' object has no attribute 'tp'

### ISSUE THREAD

**Issue by kylezh** [jessevdk/cldoc#17]
cldoc works fine in most of the time.
But I meet this error when it processing a specific file which contains many macors.

The whole traceback is as following:

```
Traceback (most recent call last):
  File "/usr/local/bin/cldoc", line 5, in <module>
    cldoc.run()
  File "/usr/local/lib/python2.7/dist-packages/cldoc/__init__.py", line 169, in run
    generate(opts, cxxflags)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/__init__.py", line 44, in generate
    generator.generate(os.path.join(opts.output, 'xml'))
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 49, in generate
    Generator.generate(self, outdir)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/generator.py", line 22, in generate
    self.generate_node(node)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 477, in generate_node
    Generator.generate_node(self, node)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/generator.py", line 27, in generate_node
    self.generate_node(child)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 471, in generate_node
    self.generate_page(node)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 438, in generate_page
    elem = self.node_to_xml(node)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 431, in node_to_xml
    chelem = self.node_to_xml(child)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 422, in node_to_xml
    self.call_type_specific(node, elem, 'to_xml')
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 403, in call_type_specific
    getattr(self, nm)(node, elem)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/generators/xml.py", line 181, in type_to_xml
    if tp.is_array:
  File "/usr/local/lib/python2.7/dist-packages/cldoc/nodes/ctype.py", line 61, in is_array
    return self.tp.kind == cindex.TypeKind.CONSTANTARRAY
AttributeError: 'TemplateType' object has no attribute 'tp'
```

Thanks,
Kyle

**Comment by jessevdk** [comment]
This should work correctly now in latest `master`.
