### ISSUE TITLE
Show graceful error messages when clang is not found

### ISSUE THREAD

**Issue by bdusell** [jessevdk/cldoc#67]
Although it should be pretty obvious that clang is needed in order to run cldoc on your system, it would be nice if there were a user-friendly message in the case that a clang installation cannot be found. 

This is the stack trace which is currently presented to the user when it fails to find `clang++` in the path:
```
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/local/bin/cldoc", line 9, in <module>                                                                                                                                            
    load_entry_point('cldoc==1.6', 'console_scripts', 'cldoc')()                                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/cldoc/__init__.py", line 57, in run                                                                                                            
    run_generate(rest)                                                                                                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/cldoc/__init__.py", line 27, in run_generate                                                                                                   
    cmdgenerate.run(args)                                                                                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/cldoc/cmdgenerate.py", line 141, in run                                                                                                        
    t = tree.Tree(opts.files, cxxflags)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/tree.py", line 40, in __init__
    self.flags = includepaths.flags(flags)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/includepaths.py", line 21, in flags
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The case when the shared library cannot be found could be improved as well, although it's clearer from the exception message what's going on:
```
Traceback (most recent call last):
  File "/usr/local/bin/cldoc", line 9, in <module>
    load_entry_point('cldoc==1.6', 'console_scripts', 'cldoc')()
  File "/usr/local/lib/python2.7/dist-packages/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/cmdgenerate.py", line 143, in run
    t.process()
  File "/usr/local/lib/python2.7/dist-packages/cldoc/tree.py", line 94, in process
    index = cindex.Index.create()
  File "/usr/local/lib/python2.7/dist-packages/cldoc/clang/cindex.py", line 1866, in create
    return Index(conf.lib.clang_createIndex(excludeDecls, 0))
  File "/usr/local/lib/python2.7/dist-packages/cldoc/clang/cindex.py", line 153, in __get__
    value = self.wrapped(instance)
  File "/usr/local/lib/python2.7/dist-packages/cldoc/clang/cindex.py", line 3100, in lib
    lib = self.get_cindex_library()
  File "/usr/local/lib/python2.7/dist-packages/cldoc/clang/cindex.py", line 3131, in get_cindex_library
    raise LibclangError(msg)
cldoc.clang.cindex.LibclangError: libclang.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```

**Comment by jessevdk** [comment]
cldoc now generates nicer error messages for both these cases.
