### ISSUE TITLE
TranslationUnitLoadError for basic example

### ISSUE THREAD

**Issue by cdeil** [jessevdk/cldoc#75]
I wanted to try out the basic example (without reading the docs), so I did:
```bash
$ cd example
$ cldoc generate -- . --output out
Processing example
Traceback (most recent call last):
  File "/Users/deil/Library/Python/2.7/bin/cldoc", line 9, in <module>
    load_entry_point('cldoc==1.6', 'console_scripts', 'cldoc')()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/cldoc-1.6-py2.7.egg/cldoc/__init__.py", line 57, in run
    run_generate(rest)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/cldoc-1.6-py2.7.egg/cldoc/__init__.py", line 27, in run_generate
    cmdgenerate.run(args)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/cldoc-1.6-py2.7.egg/cldoc/cmdgenerate.py", line 144, in run
    t.process()
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/cldoc-1.6-py2.7.egg/cldoc/tree.py", line 110, in process
    tu = self.index.parse(f, self.flags)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/cldoc-1.6-py2.7.egg/cldoc/clang/cindex.py", line 2119, in parse
    self)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/cldoc-1.6-py2.7.egg/cldoc/clang/cindex.py", line 2258, in from_source
    raise TranslationUnitLoadError("Error parsing translation unit.")
cldoc.clang.cindex.TranslationUnitLoadError: Error parsing translation unit.
```
That's not very helpful ... what's the issue ... which translation unit failed parsing in which line?
Can you improve the error message?

**Comment by seobyeongky** [comment]
You can make a detail log by adding some code at bindings-generator/clang/cindex.py file, just before throw TranslationUnitLoadError

**Comment by jessevdk** [comment]
Unfortunately we can't get more detailed information when that exception happens (we should handle it more gracefully).

In this particular case though you're passing a directory to cldoc which it doesn't understand. You should specify all the individual sources + headers just as you would call gcc/clang. I think cldoc should understand when you pass in dirs, scanning it for sources (as a convenience). Either that, or we should simply catch when you specify a directory and show an appropriate error message.

**Comment by jessevdk** [comment]
This is fixed on master. As a convenience, directories provided as sources are now recursively scanned for source files (.c, .cpp, .cc, .h, .hpp, .hh).
